# 玩家默认是否启用插件
enable: true

# 强加载持续时间 （单位：秒）（0 为不限制 直到玩家离开）
loadTime: 0

# 玩家离开后卸载的延时 （单位：秒）（0 为立即卸载）
delay: 20

# 强加载半径
radius: 1

debug: false

# 例如
# 1 :    +

# 2 :    + + +
#        + + +
#        + + +

# 3 :    + + + + +
#        + + + + +
#        + + + + +
#        + + + + +
#        + + + + +